version: "2"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/site.conf   
          
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8090:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql
        PMA_ABSOLUTE_URI: http://localhost:8080/phpmyadmin/
      
  php:
      image: php:7-fpm
      volumes:
          - ./code:/code